### ISSUE TITLE
[Bug]: the enchant vein miner causes a big lag spike, server freezes etc. Only fix was nerfing it to the dirt 2 blocks. Please do smt about it cause its essential mod for bmc1 fabric

### ISSUE THREAD

**Issue by CiriuxLT** [TheIllusiveC4/VeinMining#103]
### Minecraft Version

1.19.2

### What happened?

After some time we found out when players used it the server just freezes and lags really bad

### How do you trigger this bug?

1.
2.
3.
...
Make people use it on trees etc like over 3

### Loader

Fabric

### Loader Version

Fabric bmc

### Mod Version

Latest

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this issue and I have not heard any other reports of big lag spikes on servers from Vein Mining. It could potentially be another mod that causes it during large block break events. Does this occur if you have _only_ Vein Mining installed? In addition, does this happen in single player and other servers?

**Comment by CiriuxLT** [comment]
Hello!
It happens on a server and only when vein is activated… owner reduced the
amount of blocks it breaks to dirt and then it wont lag but we want to put
it back to how it was

**Comment by TheIllusiveC4** [comment]
Yes, but since I can't reproduce this lag and I have not gotten other reports of lag from other users, I'll need to know a bit more before I can investigate further.

1. Does this occur if you have _only_ Vein Mining installed with no other mods?
2. If you go into a single player world with the default configuration, does it still lag?
3. If you go into another server with the default configuration, does it still lag?

**Comment by CiriuxLT** [comment]
Only on this server and i cant test without other moda

**Comment by TheIllusiveC4** [comment]
If it's only on that server, and you have not or cannot test without other mods, it's likely that this is due to a mod interaction of some kind (for example, a mod that injects into block breaking behavior). Are there any mods that exist on the server and not on your client? Unfortunately, I cannot investigate further until you can either test without other mods to validate that it's an isolated issue or until you can identify which mod is causing this.
