### ISSUE TITLE
[Bug]: There no books for 2-5 lvls

### ISSUE THREAD

**Issue by Azzmurr** [TheIllusiveC4/VeinMining#104]
### Minecraft Version

1.20.1

### What happened?

Whatever I put in the config file, REI reports that only one enchantment level exists. 
The enchantment infuser mod also says that only one level exists.
Only using an anvil and combining books works

### How do you trigger this bug?

1. Change config to change lvls to 5 for example
2. Observe that in REI only one book

### Loader

Fabric

### Loader Version

0.14.22

### Mod Version

1.2.0

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this, changing the configuration levels to 5 and then loading with REI shows the books as expected:

![veinmining5](https://github.com/illusivesoulworks/veinmining/assets/29991504/88332a0a-f142-47cd-99f8-e3f20a1f27e2)

Did you test this with _only_ REI (+dependencies) and Vein Mining installed? It could be a mod conflict, although I don't know what that would be. It's also possible that REI has since addressed this on their end so also try updating REI.
