### ISSUE TITLE
[Bug]: Vein Mining mines everything without activation

### ISSUE THREAD

**Issue by Ranplex** [TheIllusiveC4/VeinMining#107]
### Minecraft Version

1.19.2

### What happened?

So basicly when i enchant anything with Veinmining it will just veinmine without activation, except for if you crouch.
I tried looking into the config files of the server and there i am missing the veinmining-client.toml, so i cant change the activation to keybind

### How do you trigger this bug?

1. 0
2.
3.
...

### Loader

Fabric

### Loader Version

Fabric 0.14.22

### Mod Version

1.19.2 1.1.1

**Comment by Anarchy079** [comment]
the clientside config needs to be changed for servers. the veinmining-client.toml is default set to "STANDING" set it to KEYBINDING

**Comment by Ranplex** [comment]
> the clientside config needs to be changed for servers. the veinmining-client.toml is default set to "STANDING" set it to KEYBINDING

If you read the description, you would know that thats not my problem. The veinmining-client.toml is not generated in my configs, thats the whole problem, i know i need to change it to keybinds, but i cant change anything which isnt even available

i tried reinstalling the Mod aswell, that did not change anything

**Comment by Ranplex** [comment]
![image](https://github.com/illusivesoulworks/veinmining/assets/146712490/173d4b24-789c-4fb7-bc8b-e7f11ceda23f)
maybe that helps to let you see, the file isnt even there to be edited

**Comment by Anarchy079** [comment]
you said "config files of the server" i said CLIENT SIDE. look in your minecraft instance configs.
i am litterally using the exact version you are using and i fixed that problem
.minecraft/config

**Comment by Anarchy079** [comment]
![config](https://github.com/illusivesoulworks/veinmining/assets/30153463/03f686b0-95d8-4647-81ec-a95d8394d3e1)

mind you the client side config set to "standing" instead of keybinding that affects the server is strange.

as in your client side config is the one the server uses instead of having their own?

**Comment by Ranplex** [comment]
> ![config](https://user-images.githubusercontent.com/30153463/271990460-03f686b0-95d8-4647-81ec-a95d8394d3e1.PNG)
> 
> mind you the client side config set to "standing" instead of keybinding that affects the server is strange.
> 
> as in your client side config is the one the server uses instead of having their own?

yeah i totally misunderstood how that works :D i am new in hosting a server, that really did help and resolve the problem.
Thanks a lot!

**Comment by Anarchy079** [comment]
i had the same problem as you did. and looked at this post and ran around looking at server and client configs. the server HAD none. and i said fuck it. *could the client file do something?* and well it fixed the problem

**Comment by TheIllusiveC4** [comment]
For future reference, the way the configs work is this:

There are three types of configuration files: client, common, and server. Client files affect clients, common files affect both, and server files affect servers. The reason that no client file is generated on a server is because it would be useless, as any behavior it changes would be client-side. By the same logic, server files on the client are useless when connected to a server (they are still generated though because they are needed for single-player worlds).

While it seems like, in this case, the client files are affecting the server, there's a little more going under the hood. The client files are only responsible for deciding how to interpret your input, which is why the activation methods are served from there. Each client is different, as each user can separately decide their own activation method while connected to the same server. Once it decides whether you can activate vein mining or not, it sends the signal to the server which processes the rest of the logic.
