### ISSUE TITLE
[Feature]: Vein Mining Tools only mine blocks for which they are specialized

### ISSUE THREAD

**Issue by Ldawsonm** [TheIllusiveC4/VeinMining#111]
### What is the new feature or improvement?

Axes can vein mine dirt, as can pickaxes and hoes. While technically this is valid since you don't need any tool to mine dirt, wouldn't it make more sense if only shovels can vein mine dirt? Further, Axes and other vein mining tools can vein mine tall grass and leaves. This should be reserved for hoes. In doing this, you're incentivizing the player to have vein mining tools of all types, as they are effective only on blocks for which they are specialized.

This could also just be a config option as I'm sure there would be some mod incompatibility here and there, such as with drills, paxels, etc.

Thank you so much for reading my feature request, I enjoy this mod a lot!

**Comment by ShadwDrgn** [comment]
in addition to this it would be great to make it so only a specific category (via tag) of item can be used to vein mein (regardless of enchantments) this way we could use ex nihilo hammers to vein mine but not pickaxes and i can't just use the hammer to mine tons of dirt like OP says. :)

**Comment by TheIllusiveC4** [comment]
> Axes can vein mine dirt, as can pickaxes and hoes. While technically this is valid since you don't need any tool to mine dirt, wouldn't it make more sense if only shovels can vein mine dirt? Further, Axes and other vein mining tools can vein mine tall grass and leaves. This should be reserved for hoes. In doing this, you're incentivizing the player to have vein mining tools of all types, as they are effective only on blocks for which they are specialized.
> 
> This could also just be a config option as I'm sure there would be some mod incompatibility here and there, such as with drills, paxels, etc.
> 
> Thank you so much for reading my feature request, I enjoy this mod a lot!

The main thing you can do, currently in 1.20.1, is use the configuration fields `requiredDestroySpeed` and `requireCorrectTool` to control which blocks can be vein mined by which tool. The former controls how fast the tool mining needs to go (with 1 being the normal speed, and higher numbers for tools that are more effective on the block) and the latter controls tools that can harvest drops from the block. A combination of these should be all you need, I think.

This might give you some pause because of how unintuitive it feels, but I will note that the coding of tool effectiveness isn't as straightforward as it seems. You can map vanilla tools to vanilla blocks fairly easily, but all of that comes undone when you have to consider modded tools and blocks. Calculating the destroy speed of a tool against a block is the most universal and direct way to calculate whether a tool is specialized for a particular block.

> in addition to this it would be great to make it so only a specific category (via tag) of item can be used to vein mein (regardless of enchantments) this way we could use ex nihilo hammers to vein mine but not pickaxes and i can't just use the hammer to mine tons of dirt like OP says. :)

The `itemsList` configuration field controls all of the items that can be enchanted with the vein mining enchantment. Is that what you're looking for?
