### ISSUE TITLE
[Bug]: Server TOML Not working correctly on a server

### ISSUE THREAD

**Issue by JdotMo** [TheIllusiveC4/VeinMining#129]
### Minecraft Version

1.20.6

### What happened?

Added sand gravel and clay to the server.toml and had no luck getting veinminer to function with it. The same configuration thats on the server works in single player. Have have also tried minecraft:, #minecraft and forge:. The TOML I uploaded works in single player but not on multiplayer

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Forge

### Loader Version

47.2..14

### Mod Version

1.4.1 + 1.20.1

### Relevant Log Outputs

[veinmining-server.log](https://github.com/illusivesoulworks/veinmining/files/15462985/veinmining-server.log)

**Comment by TheIllusiveC4** [comment]
Since it works on the single player, the configuration file should be valid. So there might be something wrong with uploading it to your server. Which folder are you uploading the configuration to in the server? Have you tried restarting the server? Is there any configuration file in your world's `serverconfig` folder that is overriding it?

**Comment by JdotMo** [comment]
The server is hosted on my personal server in my house and have restarted multi times. I doubt it is an issue with uploading it as I am editing the file directly on the server and saving it. Here is the mod pack I am playing. 

https://www.curseforge.com/minecraft/modpacks/industrial-village/files/5355153/additional-files

**Comment by JdotMo** [comment]
Okay nvm I got it working. I restarted the server again and it is working
