### ISSUE TITLE
suggestion (to help with OTHER mod compatibilitys)

### ISSUE THREAD

**Issue by iGreenDogs** [TheIllusiveC4/VeinMining#18]
Make anything that is not stone
(including)

> 1. Stone
> 2. Andisite
> 3. Diorite
> 4. etc, etc

Not vein-mineable and allow server config to add other things NOT to mine (instead of having what yes to mine hard written into the code)

**Comment by TheIllusiveC4** [comment]
I'm not what you mean. Are you talking about a blacklist for blocks that are not vein-mineable? Because you can already do that. Just put `blocksPermission` to `"BLACKLIST"` and `blocks` list to the blocks or tags that you want to disallow.

Edit: Also, the code doesn't hardcode anything at all, which is why the configs are so flexible. The code lets you mine any block by default.
