### ISSUE TITLE
Server only usage

### ISSUE THREAD

**Issue by tombl** [TheIllusiveC4/VeinMining#3]
The fabric version of this mod works almost perfectly when only installed on the server, but not the client, with only 1 flaw. The lang file defining the name of the enchantment only exists on the server, so the enchantment shows up as a blank line in tooltips.

**Comment by tombl** [comment]
I think I've found a library called [Fabric-Server-Enchantments](https://github.com/Szum123321/Fabric-Server-Enchantments) which might be useful to make this work on the server only.

**Comment by TheIllusiveC4** [comment]
I've thought about it and unfortunately I've decided not to support server-only implementations. It's a can of worms that I don't wish to open regarding syncing, since registries are coded to work from both sides, and, although it's possible, the foreseeable solutions are a bit too hacky and incomplete for my liking.
