### ISSUE TITLE
[Feature]: shaped mining

### ISSUE THREAD

**Issue by chimericdream** [TheIllusiveC4/VeinMining#43]
### What is the new feature or improvement?

I'd love to have configurable shaped mining, similar to the Ore Excavation mod. I realize that one is still updated on 1.18, but it doesn't work on Fabric, which this one does (thank you!).

I don't know what the LoE would be on this, but hopefully it is relatively straightforward enough to be worth adding.

Thanks!

**Comment by TheIllusiveC4** [comment]
To be honest, I'm not really a big fan of configurable shaped mining like that. It seems a little too immersion-breaking and I think it overcomplicates a relatively simple mechanic.

Also, the effort to implement is non-trivial so that has to be part of the consideration.

However, I can see why other people might like to have that kind of feature. I'll try and see if I can figure out a good way to accomplish this.

**Comment by chimericdream** [comment]
I can understand that. If it turns out to be a more significant undertaking than you want to spend, especially for a feature you don't particularly like, I can't blame you. Either way, thanks for considering it!

**Comment by TheIllusiveC4** [comment]
After some consideration, I've decided to decline this feature. It's just a little too much work for a feature I'm not super keen on including to begin with, unfortunately. Thanks for the suggestion though.
