### ISSUE TITLE
[Bug]: Name not appearing on books/villager tools

### ISSUE THREAD

**Issue by Centurian13** [TheIllusiveC4/VeinMining#97]
### Minecraft Version

1.19.4

### What happened?

Villagers tools that have it on there and enchantment books have no name to them. I have it installed server-side. Does this need to be configured any way specific for it to show?

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Fabric

### Loader Version

Fabric-loader-0.14.19-1.19.4

### API Version

Fabric API

### Mod Version

veinmining-quilt-1.1.2+1.19.4

**Comment by TheIllusiveC4** [comment]
Your issue is that you have it installed server-side, it needs to be on BOTH server and client to work fully. If the client doesn't have it, it has no idea what name to show you when you see it.

Also, as an aside, you seem to be using the Quilt version on Fabric when you should be using either the Fabric version or the Quilt environment.
